baseURL = "https://helloworldbr.github.io"
DefaultContentLanguage  = "pt-br"
title = "Hello World Brasil"
tags = [ "Hugo", "theme", "Crab" ]
theme="hellow"


disqusShortname = "hellow"
googleAnalytics = "UA-XXXXXX"

enableRobotsTXT = true
draft = false

[permalinks]
  posts = "/:filename"
  pages = "/:filename"


[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"


[params]
  siteName = "Hello World Brasil"
  description = "Projeto livre dos irmãos @bugotech e @tihhgoncalves   sobre tecnologia. Os conteúdos aqui divulgados para fins de ajuda a outros desenvolvedores."
