BaseURL = "https://helloworldbr.github.io/"
languageCode = "pt-br"
title = "Hello World Brasil"
theme="helloworldbr"

[permalinks]
  posts = "/:filename"
  pages = "/:filename"

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

[params]
  siteName = "Hello World Brasil"
  description = "Projeto colaborativo dos irmãos Gonçalves sobre tecnologia."
  image = "shared.png"